### ISSUE TITLE
ValueError: Both `input_dim` and `output_dim` should be positive, found input_dim 0 and output_dim 777

### ISSUE THREAD

**Issue by susannasiebert** [openvax/mhcflurry#189]
I'm trying to test pVACtools, which has a dependency to MHCflurry, with Python 3.9. I also have tensorflow 2.5.0 and keras 2.4.3 installed. When I run the command `mhcflurry-predict --alleles HLA-A*02:01 --out test.out --peptides YQDVYVELS` I get the error in the title. Do you have any idea what might be wrong with my environment to lead to this error?

**Comment by timodonnell** [comment]
Yes, it's the tensorflow version. Unfortunately the current version of MHCflurry is only compatible with tensorflow 2.2 ( see requirement here https://github.com/openvax/mhcflurry/blob/master/setup.py#L42 ). This will be fixed in the next version but requires retraining the models, so it may still be some time before we have a chance to do that.

**Comment by timodonnell** [comment]
It turned out there was a way to fix this without retraining the models. Just released the fix as mhcflurry 2.0.2, which should work with any tensorflow version >= 2.2.0. Please give it a shot and let me know if you hit any issues.
