### ISSUE TITLE
A question about the '--threshold-affinity' parameter

### ISSUE THREAD

**Issue by chenli-bioinfo** [openvax/mhcflurry#219]
Dear author, 

I was running mhcflurry using:

mhcflurry-predict-scan test.fasta --peptide-lengths 8-11 --alleles HLA-A0101 --threshold-affinity 500 --threshold-affinity-percentile 2.0 --out ./test.csv

While the percentile threshold was correctly applied, I found that affinity seemed not to be cut off:
<img width="2418" alt="WeChat3ee5c49739905c79444e6ef0df084400" src="https://github.com/openvax/mhcflurry/assets/39520131/b700b9f0-2328-4064-8b78-6fefa4b1f926">
 I was therefore wondering if I was understanding the parameters correctly. 

Thank you very much.

Chen

**Comment by timodonnell** [comment]
Thanks for reporting this, Chen. This is happening because only one quantity can be filtered, so your affinity threshold is being ignored. The library API (`Class1PresentationPredictor.predict_sequences`) makes this clear but I agree in the commandline tool this is super confusing. I am changing this now to have different semantics for the commandline tool and to apply all the filters you specify. The fix will go into the next release.
