### ISSUE TITLE
How to load own model

### ISSUE THREAD

**Issue by YiwenAI** [openvax/mhcflurry#232]
When I follow the tutorial of fitting my own model with the following link: https://openvax.github.io/mhcflurry/commandline_tutorial.html#fitting-your-own-models.

I got exactly the same model directory in the tutorial.
![image](https://github.com/openvax/mhcflurry/assets/49296865/3c1e1680-ec08-4319-808d-23a44a81bada)

While how can I load such trained model in `predictor = Class1PresentationPredictor.load()` ?  The data structure is quite different. For example, our trained Class1PresentationModel is a combination of some models, but the load function needs only one weights.csv file. 

thanks!

**Comment by timodonnell** [comment]
The instructions in the tutorial show you how to train an affinity predictor, not a presentation predictor. So you would need to load it with [Class1AffinityPredictor.load()]( https://openvax.github.io/mhcflurry/api.html#mhcflurry.Class1AffinityPredictor.load).

**Comment by timodonnell** [comment]
Model training and selection is unfortunately not very well documented and you'll have to follow the scripts I used. Take a look here for how you can do this: https://github.com/openvax/mhcflurry/blob/master/downloads-generation/models_class1_pan/GENERATE.sh

Basically you can specify `--held-out-measurements-per-allele-fraction-and-max 0.25 100` and `--num-folds 4 ` when you call `mhcflurry-class1-train-pan-allele-models` so that some data is held out for model selection.
